"""
AppArmor LSP – constants: keywords, permissions, capabilities, abstractions, etc.
"""

from __future__ import annotations

# ── Top-level / structural keywords ──────────────────────────────────────────

PROFILE_KEYWORDS: list[str] = [
    "profile",
    "hat",
    "include",
    "alias",
    "variable",
    "if",
    "else",
    "flags",
    "complain",
    "enforce",
    "kill",
    "unconfined",
    "prompt",
]

RULE_KEYWORDS: list[str] = [
    "capability",
    "network",
    "signal",
    "ptrace",
    "mount",
    "umount",
    "remount",
    "pivot_root",
    "unix",
    "dbus",
    "file",
    "link",
    "owner",
    "deny",
    "audit",
    "change_profile",
    "change_hat",
    "rlimit",
    "userns",
    "io_uring",
    "mqueue",
]

ALL_KEYWORDS = sorted(set(PROFILE_KEYWORDS + RULE_KEYWORDS))

# ── File permissions ──────────────────────────────────────────────────────────

FILE_PERMISSIONS: dict[str, str] = {
    "r": "Read",
    "w": "Write (and implicitly truncate/create)",
    "a": "Append (write without truncate)",
    "x": "Execute (unconfined, use with caution)",
    "m": "Memory-map executable (mmap PROT_EXEC)",
    "k": "Lock (fcntl and flock)",
    "l": "Hard-link",
    "d": "Delete / unlink",
    # Execute modifiers
    "ix": "Execute and inherit current profile",
    "ux": "Execute unconfined (unsafe – no child profile)",
    "Ux": "Execute unconfined (safe – sanitise environment)",
    "px": "Execute under a named profile (requires matching profile)",
    "Px": "Execute under named profile (safe – sanitise environment)",
    "cx": "Execute under a child profile",
    "Cx": "Execute under child profile (safe)",
    "pix": "Execute under named profile or inherit",
    "Pix": "Execute under named profile (safe) or inherit",
    "cix": "Execute under child profile or inherit",
    "Cix": "Execute under child profile (safe) or inherit",
    "pux": "Execute under named profile or unconfined",
    "Pux": "Execute under named profile (safe) or unconfined",
    "cux": "Execute under child profile or unconfined",
    "Cux": "Execute under child profile (safe) or unconfined",
}

# ── Linux capabilities ────────────────────────────────────────────────────────

CAPABILITIES: list[str] = [
    "audit_control",
    "audit_read",
    "audit_write",
    "block_suspend",
    "bpf",
    "checkpoint_restore",
    "chown",
    "dac_override",
    "dac_read_search",
    "fowner",
    "fsetid",
    "ipc_lock",
    "ipc_owner",
    "kill",
    "lease",
    "linux_immutable",
    "mac_admin",
    "mac_override",
    "mknod",
    "net_admin",
    "net_bind_service",
    "net_broadcast",
    "net_raw",
    "perfmon",
    "setfcap",
    "setgid",
    "setpcap",
    "setuid",
    "sys_admin",
    "sys_boot",
    "sys_chroot",
    "sys_module",
    "sys_nice",
    "sys_pacct",
    "sys_ptrace",
    "sys_rawio",
    "sys_resource",
    "sys_time",
    "sys_tty_config",
    "syslog",
    "wake_alarm",
]

# ── Network ───────────────────────────────────────────────────────────────────

NETWORK_FAMILIES: list[str] = [
    "inet",
    "inet6",
    "unix",
    "netlink",
    "packet",
    "bridge",
    "bluetooth",
    "can",
    "caif",
    "alg",
    "nfc",
    "vsock",
    "kcm",
    "qipcrtr",
    "smc",
    "xdp",
    "mctp",
    "mpls",
    "tipc",
]

NETWORK_TYPES: list[str] = [
    "stream",
    "dgram",
    "seqpacket",
    "rdm",
    "raw",
    "packet",
]

NETWORK_PROTOCOLS: list[str] = [
    "tcp",
    "udp",
    "icmp",
    "icmpv6",
    "raw",
]

# ── Signal ────────────────────────────────────────────────────────────────────

SIGNAL_PERMISSIONS: list[str] = [
    "send",
    "receive",
    "r",
    "w",
    "rw",
]

SIGNAL_NAMES: list[str] = [
    "hup",
    "int",
    "quit",
    "ill",
    "trap",
    "abrt",
    "bus",
    "fpe",
    "kill",
    "usr1",
    "segv",
    "usr2",
    "pipe",
    "alrm",
    "term",
    "chld",
    "cont",
    "stop",
    "tstp",
    "ttin",
    "ttou",
    "urg",
    "xcpu",
    "xfsz",
    "vtalrm",
    "prof",
    "winch",
    "io",
    "pwr",
    "sys",
    "exists",
    "rtmin",
    "rtmax",
]

# ── Ptrace ────────────────────────────────────────────────────────────────────

PTRACE_PERMISSIONS: list[str] = [
    "read",
    "readby",
    "trace",
    "tracedby",
]

# ── Mount ─────────────────────────────────────────────────────────────────────

MOUNT_OPTIONS: list[str] = [
    "ro",
    "rw",
    "suid",
    "nosuid",
    "dev",
    "nodev",
    "exec",
    "noexec",
    "sync",
    "async",
    "remount",
    "mand",
    "nomand",
    "dirsync",
    "noatime",
    "nodiratime",
    "bind",
    "rbind",
    "move",
    "silent",
    "acl",
    "noacl",
    "relatime",
    "iversion",
    "noiversion",
    "strictatime",
    "lazytime",
    "nolazytime",
    "unbindable",
    "runbindable",
    "private",
    "rprivate",
    "shared",
    "rshared",
    "slave",
    "rslave",
]

# ── DBus ──────────────────────────────────────────────────────────────────────

DBUS_PERMISSIONS: list[str] = [
    "send",
    "receive",
    "bind",
    "r",
    "w",
    "rw",
    "read",
    "write",
]

DBUS_BUSES: list[str] = [
    "system",
    "session",
    "accessibility",
]

# ── Unix socket ───────────────────────────────────────────────────────────────

UNIX_PERMISSIONS: list[str] = [
    "create",
    "accept",
    "bind",
    "connect",
    "listen",
    "read",
    "write",
    "send",
    "receive",
    "getsockname",
    "getpeername",
    "getsockopt",
    "setsockopt",
    "getattr",
    "setattr",
    "shutdown",
]

UNIX_TYPES: list[str] = [
    "stream",
    "dgram",
    "seqpacket",
]

# ── Profile flags ─────────────────────────────────────────────────────────────

PROFILE_FLAGS: list[str] = [
    "complain",
    "enforce",
    "kill",
    "unconfined",
    "prompt",
    "mediate_deleted",
    "attach_disconnected",
    "attach_disconnected.path",
    "chroot_relative",
    "debug",
    "interruptible",
    "no_attach_disconnected",
]

# ── Include abstractions ──────────────────────────────────────────────────────

ABSTRACTIONS: list[str] = [
    "abstractions/authentication",
    "abstractions/base",
    "abstractions/bash",
    "abstractions/consoles",
    "abstractions/cups-client",
    "abstractions/dbus",
    "abstractions/dbus-accessibility",
    "abstractions/dbus-accessibility-strict",
    "abstractions/dbus-network-manager-strict",
    "abstractions/dbus-session",
    "abstractions/dbus-session-strict",
    "abstractions/dbus-strict",
    "abstractions/dconf",
    "abstractions/dovecot-common",
    "abstractions/evince",
    "abstractions/fcitx",
    "abstractions/fcitx-strict",
    "abstractions/fonts",
    "abstractions/freedesktop.org",
    "abstractions/gconf",
    "abstractions/gconf-write",
    "abstractions/gjs",
    "abstractions/gnome",
    "abstractions/gnupg",
    "abstractions/hosts_access",
    "abstractions/ibus",
    "abstractions/kde",
    "abstractions/kde-globals-write",
    "abstractions/kde-icon-cache-write",
    "abstractions/kde-open5",
    "abstractions/kerberosclient",
    "abstractions/ldapclient",
    "abstractions/libpam-systemd",
    "abstractions/likewise",
    "abstractions/lxc/container-base",
    "abstractions/lxc/start-container",
    "abstractions/mdns",
    "abstractions/mir",
    "abstractions/mount",
    "abstractions/mozc",
    "abstractions/mysql",
    "abstractions/nameservice",
    "abstractions/nis",
    "abstractions/nss-systemd",
    "abstractions/nvidia",
    "abstractions/opencl",
    "abstractions/openssl",
    "abstractions/orbit2",
    "abstractions/p11-kit",
    "abstractions/passwd",
    "abstractions/perl",
    "abstractions/php",
    "abstractions/postfix-common",
    "abstractions/private-files",
    "abstractions/private-files-strict",
    "abstractions/python",
    "abstractions/qt5",
    "abstractions/qt5-compose-cache-write",
    "abstractions/qt5-settings-write",
    "abstractions/qt5-shader-cache",
    "abstractions/ruby",
    "abstractions/samba",
    "abstractions/samba-heimdal",
    "abstractions/snap_browsers",
    "abstractions/ssl_certs",
    "abstractions/ssl_keys",
    "abstractions/svn-repositories",
    "abstractions/system-auth",
    "abstractions/totem",
    "abstractions/ubuntu-buntish",
    "abstractions/ubuntu-browsers",
    "abstractions/ubuntu-browsers.d/chromium-browser",
    "abstractions/ubuntu-browsers.d/firefox",
    "abstractions/ubuntu-browsers.d/java",
    "abstractions/ubuntu-browsers.d/text-editors",
    "abstractions/ubuntu-browsers.d/ubuntu-integration",
    "abstractions/ubuntu-email",
    "abstractions/ubuntu-helpers",
    "abstractions/ubuntu-unity7",
    "abstractions/ubuntu-unity7-base",
    "abstractions/ubuntu-unity7-settings",
    "abstractions/ubuntu-unity7-systray",
    "abstractions/ubuntu-xterm",
    "abstractions/user-download",
    "abstractions/user-mail",
    "abstractions/user-manpages",
    "abstractions/user-tmp",
    "abstractions/user-write",
    "abstractions/vaapi",
    "abstractions/video",
    "abstractions/vulkan",
    "abstractions/wayland",
    "abstractions/web-data",
    "abstractions/webengine",
    "abstractions/winbind",
    "abstractions/wutmp",
    "abstractions/X",
    "abstractions/xad",
    "abstractions/xdg-desktop",
    "abstractions/xdg-open",
    "abstractions/xml",
]

# ── Common AppArmor variables ─────────────────────────────────────────────────

VARIABLES: dict[str, str] = {
    "@{PROC}": "Path to /proc (typically /proc)",
    "@{HOME}": "User home directories glob (e.g. /home/*/ /root/)",
    "@{HOMEDIRS}": "Parent of home directories (e.g. /home/)",
    "@{run}": "/run or /var/run",
    "@{sys}": "Path to /sys",
    "@{etc_ro}": "/etc (read-only locations)",
    "@{multiarch}": "Multi-arch tuple (e.g. x86_64-linux-gnu)",
    "@{multiarch32}": "32-bit multi-arch tuple",
    "@{pids}": "PID glob [1-9]*",
    "@{tid}": "Thread-ID glob [1-9]*",
    "@{uid}": "UID glob [0-9]*",
    "@{gid}": "GID glob [0-9]*",
    "@{int}": "Integer glob [0-9]*",
    "@{hex}": "Hex string glob [0-9a-fA-F]*",
    "@{rand8}": "8-char random hex string",
    "@{user_dirs}": "XDG user directories",
    "@{XDG_DESKTOP_DIR}": "XDG desktop directory",
    "@{XDG_DOCUMENTS_DIR}": "XDG documents directory",
    "@{XDG_DOWNLOAD_DIR}": "XDG download directory",
    "@{XDG_MUSIC_DIR}": "XDG music directory",
    "@{XDG_PICTURES_DIR}": "XDG pictures directory",
    "@{XDG_PUBLICSHARE_DIR}": "XDG public share directory",
    "@{XDG_TEMPLATES_DIR}": "XDG templates directory",
    "@{XDG_VIDEOS_DIR}": "XDG videos directory",
    "@{XDG_CONFIG_DIRS}": "XDG config directories",
    "@{XDG_CONFIG_HOME}": "XDG config home",
    "@{XDG_CACHE_HOME}": "XDG cache home",
    "@{XDG_DATA_DIRS}": "XDG data directories",
    "@{XDG_DATA_HOME}": "XDG data home",
    "@{XDG_RUNTIME_DIR}": "XDG runtime directory",
    "@{XDG_STATE_HOME}": "XDG state home",
}

# ── Resource limits ───────────────────────────────────────────────────────────

RLIMIT_RESOURCES: list[str] = [
    "rlimit as",
    "rlimit core",
    "rlimit cpu",
    "rlimit data",
    "rlimit fsize",
    "rlimit locks",
    "rlimit memlock",
    "rlimit msgqueue",
    "rlimit nice",
    "rlimit nofile",
    "rlimit nproc",
    "rlimit rss",
    "rlimit rtprio",
    "rlimit rttime",
    "rlimit sigpending",
    "rlimit stack",
]

# ── Indentation used by the formatter ────────────────────────────────────────

DEFAULT_INDENT = "  "  # two spaces
