name: apparmor-language-server
adopt-info: apparmor-language-server
base: core24
summary: Language server for AppArmor profiles
description: |
  This is a language server for AppArmor profiles, which provides features such as
  code completion, linting, and diagnostics for AppArmor profiles. It is designed
  to be used with editors that support the Language Server Protocol (LSP), such as
  Visual Studio Code, Vim, and Emacs.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
source-code: https://github.com/alexmurray/apparmor-language-server
issues: https://github.com/alexmurray/apparmor-language-server/issues
website: https://github.com/alexmurray/apparmor-language-server
icon: snap/icon.svg

apps:
  apparmor-language-server:
    command: bin/apparmor-language-server
    plugs:
      - network-bind # for --tcp
      - network
      - home
      - etc-apparmor-d

plugs:
  etc-apparmor-d:
    interface: system-files
    read:
      - /etc/apparmor.d
parts:
  apparmor-language-server:
    plugin: python
    source: .
    build-packages:
      - git
    build-snaps:
      - yq
    override-build: |
      craftctl default
      # read version from pyproject.toml and set it as the snap version along
      # with the git short hash
      craftctl set version=$(yq ".project.version" pyproject.toml)-$(git rev-parse --short HEAD)
